# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict

      # TODO: consider enabling these in the future (will want to rewrite a lot of files right now)
      #- id: end-of-file-fixer
      #- id: mixed-line-ending
      #- id: trailing-whitespace

      # TODO: consider this (will need to change dev_tools/release/helpers.py to skip hooks):
      #- id: no-commit-to-branch
      #  args:
      #    - '--branch=develop'
      #    - '--pattern=release/.*'
      #  stages:
      #    - commit
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        exclude: 'dorado/3rdparty/'
        args:
          - '--target-version=py310'
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v19.1.7'
    hooks:
      - id: clang-format
        exclude: '^dorado/3rdparty/(?!kadayashi/)'
  - repo: https://github.com/falkben/pre-commit-prepend-jira-issue
    rev: 'v0.0.2'
    hooks:
      - id: prepend-jira-issue
        name: prepend jira issue
        stages: [prepare-commit-msg]
  - repo: local
    hooks:
    -   id: jira-ticket
        name: check for jira ticket
        language: pygrep
        entry: '\A(?!\[?[A-Z]+-[0-9]+\]?)'
        args: [--multiline]
        stages: [commit-msg]
    -   id: shell-tests-active
        name: check all toggleable shell tests are active
        language: script
        entry: tests/check_shell_tests_active.sh
        files: ^tests/.*\.sh$
        pass_filenames: false
        always_run: true


# NB: by default, pre-commit only installs the pre-commit hook ("commit" stage),
# but you can tell `pre-commit install` to install other hooks using e.g. `-t commit-msg`
# This set of default stages ensures we don't slow down or break other git operations
# even if you install hooks for them.
default_stages:
  - pre-commit
  - pre-merge-commit
  - manual

# vi:et:sw=2:sts=2:
